#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: v2
appVersion: "4.0.8"
description: Apache Pulsar Helm chart for Kubernetes
name: pulsar
version: 4.4.0
kubeVersion: ">=1.25.0-0"
home: https://pulsar.apache.org
sources:
  - https://github.com/apache/pulsar
  - https://github.com/apache/pulsar-helm-chart
icon: https://pulsar.apache.org/img/pulsar.svg
maintainers:
  - name: The Apache Pulsar Team
    email: dev@pulsar.apache.org
dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.38.x
    repository: https://victoriametrics.github.io/helm-charts/
    condition: victoria-metrics-k8s-stack.enabled
