#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.components.dekaf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pulsar.fullname" . }}-{{ .Values.dekaf.component }}
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.dekaf.component }}
  annotations:
    {{- toYaml .Values.dekaf.deployment.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pulsar.matchLabels" . | nindent 6 }}
      component: {{ .Values.dekaf.component }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "pulsar.template.labels" . | nindent 8 }}
        component: {{ .Values.dekaf.component }}
      annotations: {{ .Values.dekaf.deployment.podAnnotations | toYaml | nindent 8 }}
    spec:
      {{- if .Values.dekaf.deployment.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.dekaf.deployment.nodeSelector | indent 10 }}
      {{- end }}

      {{- if .Values.dekaf.deployment.tolerations }}
      tolerations:
        {{ toYaml .Values.dekaf.deployment.tolerations | indent 8 }}
      {{- end }}

      containers:
        - name: dekaf
          image: "{{ .Values.images.dekaf.repository }}:{{ .Values.images.dekaf.tag }}"
          imagePullPolicy: "{{ template "pulsar.imagePullPolicy" (dict "image" .Values.images.dekaf "root" .) }}"
          env:
          - name: DEKAF_PULSAR_WEB_URL
            value: "http://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}:{{ .Values.broker.ports.http }}"
          - name: DEKAF_PULSAR_BROKER_URL
            value: "pulsar://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}:{{ .Values.broker.ports.pulsar }}"

          {{- if .Values.dekaf.deployment.extraEnv }}
            {{- toYaml .Values.dekaf.deployment.extraEnv | nindent 10 }}
          {{- end }}

          ports:
            - containerPort: 8090
              name: http

          resources:
            {{- toYaml .Values.dekaf.deployment.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.dekaf.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.dekaf.deployment.readinessProbe | nindent 12 }}

          {{- if .Values.dekaf.persistence.enabled }}
          volumeMounts:
            - name: {{ template "pulsar.fullname" . }}-{{ .Values.dekaf.component }}-library
              mountPath: /dekaf/data/library
          {{- end }}

          {{- if .Values.dekaf.deployment.extraVolumeMounts }}
            {{- toYaml .Values.dekaf.deployment.extraVolumeMounts | nindent 12 }}
          {{- end }}

      {{- toYaml .Values.dekaf.deployment.extraContainers | nindent 8 }}

      volumes:
      {{- if .Values.dekaf.persistence.enabled }}
      - name: {{ template "pulsar.fullname" . }}-{{ .Values.dekaf.component }}-library
        persistentVolumeClaim:
          claimName: {{ template "pulsar.fullname" . }}-{{ .Values.dekaf.component }}-library
      {{- end }}

      {{- if .Values.dekaf.deployment.extraVolumes }}
        {{- toYaml .Values.dekaf.deployment.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}