{{- if .Values.dekaf.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pulsar.fullname" . }}-{{ .Values.dekaf.component }}-library
  namespace: {{ template "pulsar.namespace" . }}

  {{- with .Values.dekaf.persistence.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    {{- if .Values.dekaf.persistence.labels }}
    {{- toYaml .Values.dekaf.persistence.labels | nindent 4 }}
    {{- end }}

spec:
  accessModes:
  {{- toYaml .Values.dekaf.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: "{{ .Values.dekaf.persistence.size }}"
  storageClassName: {{ .Values.dekaf.persistence.storageClass }}
{{- end }}