#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.components.dekaf }}
{{- if ((.Values.dekaf).persistence).enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pulsar.fullname" . }}-{{ template "dekaf.component" . }}-library
  namespace: {{ template "pulsar.namespace" . }}

  {{- with ((.Values.dekaf).persistence).annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    {{- if ((.Values.dekaf).persistence).labels }}
    {{- toYaml .Values.dekaf.persistence.labels | nindent 4 }}
    {{- end }}

spec:
  accessModes:
  {{- (((.Values.dekaf).persistence).accessModes | default (list "ReadWriteOnce")) | toYaml | nindent 4 }}
  resources:
    requests:
      storage: "{{ ((.Values.dekaf).persistence).size | default "2Gi" }}"
  storageClassName: {{ ((.Values.dekaf).persistence).storageClass | default nil }}
{{- end }}
{{- end }}