#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if or (and .Values.useReleaseStatus .Release.IsInstall) .Values.initialize }}
{{- if .Values.components.broker }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.pulsar_metadata.component }}
spec:
# This feature was previously behind a feature gate for several Kubernetes versions and will default to true in 1.23 and beyond
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
{{- if and .Values.job.ttl.enabled (semverCompare ">=1.23-0" .Capabilities.KubeVersion.Version) }}
  ttlSecondsAfterFinished: {{ .Values.job.ttl.secondsAfterFinished | default 600 }}
{{- end }}
  template:
    spec:
    {{- include "pulsar.imagePullSecrets" . | nindent 6 }}
    {{- if .Values.pulsar_metadata.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.pulsar_metadata.nodeSelector | indent 8 }}
    {{- end }}
      initContainers:
      {{- if and .Values.components.zookeeper .Values.pulsar_metadata.waitZookeeperTimeout (gt (.Values.pulsar_metadata.waitZookeeperTimeout | int) 0) }}
      {{- if .Values.pulsar_metadata.configurationStore }}
      - name: wait-zk-cs-ready
        image: "{{ template "pulsar.imageFullName" (dict "image" .Values.pulsar_metadata.image "root" .) }}"
        imagePullPolicy: "{{ template "pulsar.imagePullPolicy" (dict "image" .Values.pulsar_metadata.image "root" .) }}"
        resources: {{ toYaml .Values.initContainer.resources | nindent 10 }}
        command: ["timeout", "{{ .Values.pulsar_metadata.waitZookeeperTimeout }}", "sh", "-c"]
        args:
          - |
            until nslookup {{ .Values.pulsar_metadata.configurationStore}}; do
              sleep 3;
            done;
      {{- end }}
      - name: wait-zk-metastore-ready
        image: "{{ template "pulsar.imageFullName" (dict "image" .Values.pulsar_metadata.image "root" .) }}"
        imagePullPolicy: "{{ template "pulsar.imagePullPolicy" (dict "image" .Values.pulsar_metadata.image "root" .) }}"
        resources: {{ toYaml .Values.initContainer.resources | nindent 10 }}
        command: ["timeout", "{{ .Values.pulsar_metadata.waitZookeeperTimeout }}", "sh", "-c"]
        args:
          - |
            {{- if $zk := .Values.pulsar_metadata.userProvidedZookeepers }}
            export PULSAR_MEM="-Xmx128M";
            until timeout 15 bin/pulsar zookeeper-shell -server {{ $zk }} ls {{ or .Values.metadataPrefix "/" }}; do
              echo "user provided zookeepers {{ $zk }} are unreachable... check in 3 seconds ..." && sleep 3;
            done;
            {{ else if .Values.components.zookeeper }}
            until nslookup {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ add (.Values.zookeeper.replicaCount | int) -1 }}.{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}.{{ template "pulsar.namespace" . }}; do
              sleep 3;
            done;
            {{- end }}
      {{- end }}
      {{- if and .Values.components.oxia .Values.pulsar_metadata.waitOxiaTimeout (gt (.Values.pulsar_metadata.waitOxiaTimeout | int) 0) }}
      - name: wait-oxia-ready
        image: "{{ template "pulsar.imageFullName" (dict "image" .Values.pulsar_metadata.image "root" .) }}"
        imagePullPolicy: "{{ template "pulsar.imagePullPolicy" (dict "image" .Values.pulsar_metadata.image "root" .) }}"
        resources: {{ toYaml .Values.initContainer.resources | nindent 10 }}
        command: ["timeout", "{{ .Values.pulsar_metadata.waitOxiaTimeout }}", "sh", "-c"]
        args:
          - |
            until nslookup {{ template "pulsar.oxia.server.service" . }}; do
              sleep 3;
            done;
      {{- end }}
      {{- if and .Values.pulsar_metadata.waitBookkeeperTimeout (gt (.Values.pulsar_metadata.waitBookkeeperTimeout | int) 0) }}
      # This initContainer will wait for bookkeeper initnewcluster to complete
      # before initializing pulsar metadata
      - name: pulsar-bookkeeper-verify-clusterid
        image: {{ template "pulsar.imageFullName" (dict "image" .Values.pulsar_metadata.image "root" .) }}
        imagePullPolicy: {{ template "pulsar.imagePullPolicy" (dict "image" .Values.pulsar_metadata.image "root" .) }}
        resources: {{ toYaml .Values.initContainer.resources | nindent 10 }}
        command: ["timeout", "{{ .Values.pulsar_metadata.waitBookkeeperTimeout }}", "sh", "-c"]
        args:
        - |
          bin/apply-config-from-env.py conf/bookkeeper.conf;
          echo Default BOOKIE_MEM settings are set very high, which can cause the init container to fail.;
          echo Setting the memory to a lower value to avoid OOM as operations below are not memory intensive.;
          export BOOKIE_MEM="-Xmx128M";
          {{- include "pulsar.toolset.zookeeper.tls.settings" . | nindent 10 }}
          until timeout 15 bin/bookkeeper shell whatisinstanceid; do
            sleep 3;
          done;
        envFrom:
        - configMapRef:
            name: {{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}
        volumeMounts:
        {{- include "pulsar.toolset.certs.volumeMounts" . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}
        image: {{ template "pulsar.imageFullName" (dict "image" .Values.pulsar_metadata.image "root" .) }}
        imagePullPolicy: {{ template "pulsar.imagePullPolicy" (dict "image" .Values.pulsar_metadata.image "root" .) }}
      {{- if .Values.pulsar_metadata.resources }}
        resources:
{{ toYaml .Values.pulsar_metadata.resources | indent 10 }}
      {{- end }}
        command: ["timeout", "{{ .Values.pulsar_metadata.initTimeout | default 60 }}", "sh", "-c"]
        {{- if .Values.components.zookeeper }}
        args:
          - | # Use the pipe character for the YAML multiline string. Workaround for kubernetes-sigs/kustomize#4201
            {{- include "pulsar.toolset.zookeeper.tls.settings" . | nindent 12 }}
            export PULSAR_MEM="-Xmx128M";
            bin/pulsar initialize-cluster-metadata \
              --cluster {{ template "pulsar.cluster.name" . }} \
              --zookeeper {{ template "pulsar.zookeeper.connect" . }}{{ .Values.metadataPrefix }} \
            {{- if .Values.pulsar_metadata.configurationStore }}
              --configuration-store {{ template "pulsar.configurationStore.connect" . }}{{ .Values.pulsar_metadata.configurationStoreMetadataPrefix }} \
            {{- else }}
              --configuration-store {{ template "pulsar.zookeeper.connect" . }}{{ .Values.metadataPrefix }} \
            {{- end }}
              --web-service-url http://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.http }}/ \
              --web-service-url-tls https://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.https }}/ \
              --broker-service-url pulsar://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.pulsar }}/ \
              --broker-service-url-tls pulsar+ssl://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.pulsarssl }}/ ;
            {{- if .Values.extraInitCommand }}
              {{ .Values.extraInitCommand }}
            {{- end }}
        {{- else if .Values.components.oxia }}
        args:
          - | # Use the pipe character for the YAML multiline string. Workaround for kubernetes-sigs/kustomize#4201
            export PULSAR_MEM="-Xmx128M";
            bin/pulsar initialize-cluster-metadata \
              --cluster {{ template "pulsar.cluster.name" . }} \
              --metadata-store "{{ template "pulsar.oxia.metadata.url.broker" . }}" \
              --configuration-store "{{ template "pulsar.oxia.metadata.url.broker" . }}" \
              --web-service-url http://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.http }}/ \
              --web-service-url-tls https://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.https }}/ \
              --broker-service-url pulsar://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.pulsar }}/ \
              --broker-service-url-tls pulsar+ssl://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.pulsarssl }}/ ;
            {{- if .Values.extraInitCommand }}
              {{ .Values.extraInitCommand }}
            {{- end }}
        {{- end }}
        volumeMounts:
        {{- include "pulsar.toolset.certs.volumeMounts" . | nindent 10 }}
      volumes:
      {{- include "pulsar.toolset.certs.volumes" . | nindent 8 }}
      restartPolicy: OnFailure
      {{- if .Values.pulsar_metadata.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.pulsar_metadata.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.pulsar_metadata.tolerations }}
      tolerations:
{{ toYaml .Values.pulsar_metadata.tolerations | indent 8 }}
      {{- end }}
{{- end }}
{{- end }}
